version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        applies-to: "version-updates"
        patterns:
          - "*"
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directories:
      - "/infra/accounts"
      - "/infra/databases"
      - "/infra/environments"
      - "/infra/modules/*"
  - package-ecosystem: "npm"
    directory: "/assets"
    schedule:
      interval: "weekly"
    groups:
      nodejs:
        applies-to: "version-updates"
        patterns:
          - "*"
