#!/bin/bash
#USAGE arg "<environment_name>"
#USAGE flag "--image-tag <image_tag>" help="Tag to use for the image (default is the Git SHA)"
#USAGE flag "--build-dir <path>" help="Optional other directory to build from"
#USAGE flag "--push" help="Whether to push the image to the remote repository"
set -euo pipefail

environment="${usage_environment_name?}"
source mise-tasks/infra/account-information "$environment"

image_flag="--load"

if [[ "${usage_push:-false}" == "true" && -z "$host" ]]; then
  aws ecr get-login-password --region "$region" | docker login --username AWS --password-stdin "$repository_url"  > /dev/null
  image_flag="--push"
fi

if [[ -n "$host" ]]; then
  builder="$project_name-$host"

  if ! docker context inspect "$builder" >/dev/null 2>&1; then
    docker context create "$builder" --docker "host=ssh://ubuntu@$host"
  fi
  export DOCKER_CONTEXT="$builder"
fi

[[ -n "${usage_build_dir:-}" ]] && cd "$usage_build_dir"

image_tag="${usage_image_tag:-}"
if [ -z "${usage_image_tag:-}" ]; then
	image_tag=${repository_url}:$(git rev-parse HEAD)
fi

build_args=(".")
if [ -n "${GITHUB_WORKFLOW:-}" ]; then
    # shellcheck disable=SC2054 # commas are for the Docker argument
    build_args+=(--cache-to type=gha,mode=max,ignore-error=true --cache-from type=gha)
else
  true
  # build_args+=(--cache-to="type=inline" --cache-from="type=inline")
fi

echo "image_tag=$image_tag"

if docker manifest inspect "$image_tag" >/dev/null 2>&1; then
    echo Tag already exists, not rebuilding.
else
    set -x # log the Docker command
    docker buildx build --target release --platform linux/arm64 --tag "$image_tag" "$image_flag" "${build_args[@]}"
fi
