defmodule GtfsPlanner.Gtfs.StationReport2.NamingChecks do
  @moduledoc """
  Naming convention checks for station report.

  Validates title case, jargon usage, and stop_id prefix conventions
  for generic nodes and boarding areas.
  """

  alias GtfsPlanner.Gtfs.StationReport2.Helpers

  @test_tokens ~w[test temp placeholder dummy todo tbd delete sample]

  @prefix_type_map [
    {"entrance_", 2},
    {"node_", 3},
    {"boarding_", 4}
  ]

  @transit_terms MapSet.new(~w[
    entrance exit node boarding platform station gate mezzanine
    concourse lobby elevator escalator stair stairs walkway
    tunnel bridge corridor passage hallway overpass underpass
    north south east west upper lower level ground street
    main central transfer landing turn turnstile style height
  ])

  @name_minor_words MapSet.new(~w[of the and in on at to for a an entrance exit station platform])

  @jargon_patterns [
    {"mezzanine_unpaid", ~r/\bmezzanine unpaid\b/},
    {"mezzanine_paid", ~r/\bmezzanine paid\b/},
    {"fare_line", ~r/\bfare line\b/},
    {"fareline", ~r/\bfareline\b/},
    {"unpaid", ~r/\bunpaid\b/},
    {"paid", ~r/\bpaid\b/}
  ]

  @doc """
  Returns naming convention validation items for a station and its child stops.
  """
  @spec validate(map(), [map()]) :: [map()]
  def validate(station, child_stops) do
    all_stops = [station | child_stops]
    station_id = station.stop_id

    [
      title_case_check(all_stops),
      jargon_check(all_stops),
      node_prefix_check(child_stops, station_id),
      boarding_prefix_check(child_stops, station_id),
      entrance_prefix_check(child_stops, station_id),
      prefix_type_mismatch_check(child_stops, station_id),
      test_placeholder_check(all_stops),
      direction_mismatch_check(all_stops),
      duplicate_id_tokens_check(all_stops),
      autogenerated_name_check(all_stops),
      parent_name_consistency_check(station, child_stops),
      stop_id_typo_check(all_stops)
    ]
  end

  defp title_case_check(stops) do
    flagged =
      stops
      |> Enum.filter(&Helpers.present?(&1.stop_name))
      |> Enum.map(fn stop ->
        expected = Helpers.title_case(stop.stop_name)
        {stop.stop_id, stop.stop_name, expected}
      end)
      |> Enum.filter(fn {_id, actual, expected} -> actual != expected end)
      |> Enum.map(fn {id, _actual, expected} ->
        %{id: id, reason: "expected \"#{expected}\""}
      end)

    Helpers.item(
      "naming_title_case",
      "Stop names use title case",
      if(flagged == [], do: :pass, else: :warn),
      :convention,
      length(flagged),
      flagged
    )
  end

  defp jargon_check(stops) do
    flagged =
      stops
      |> Enum.filter(&Helpers.present?(&1.stop_name))
      |> Enum.map(fn stop ->
        normalized = normalize_name(stop.stop_name)

        matches =
          @jargon_patterns
          |> Enum.flat_map(fn {label, pattern} ->
            if Regex.match?(pattern, normalized), do: [label], else: []
          end)

        {stop.stop_id, matches}
      end)
      |> Enum.filter(fn {_id, matches} -> matches != [] end)
      |> Enum.map(fn {id, matches} ->
        %{id: id, reason: "contains: #{Enum.join(matches, ", ")}"}
      end)

    Helpers.item(
      "naming_jargon",
      "Stop names avoid internal jargon",
      if(flagged == [], do: :pass, else: :warn),
      :convention,
      length(flagged),
      flagged
    )
  end

  defp normalize_name(name) do
    name
    |> String.downcase()
    |> String.replace(~r/[_-]+/, " ")
    |> String.replace(~r/\s+/, " ")
    |> String.trim()
  end

  defp node_prefix_check(child_stops, station_id) do
    flagged =
      child_stops
      |> Enum.filter(&(&1.location_type == 3))
      |> Enum.reject(&has_type_prefix?(&1.stop_id, "node_", station_id))
      |> Enum.map(& &1.stop_id)

    Helpers.item(
      "naming_node_prefix",
      "Generic nodes use node_ prefix",
      if(flagged == [], do: :pass, else: :warn),
      :convention,
      length(flagged),
      flagged
    )
  end

  defp boarding_prefix_check(child_stops, station_id) do
    flagged =
      child_stops
      |> Enum.filter(&(&1.location_type == 4))
      |> Enum.reject(&has_type_prefix?(&1.stop_id, "boarding_", station_id))
      |> Enum.map(& &1.stop_id)

    Helpers.item(
      "naming_boarding_prefix",
      "Boarding areas use boarding_ prefix",
      if(flagged == [], do: :pass, else: :warn),
      :convention,
      length(flagged),
      flagged
    )
  end

  defp entrance_prefix_check(child_stops, station_id) do
    flagged =
      child_stops
      |> Enum.filter(&(&1.location_type == 2))
      |> Enum.reject(&has_type_prefix?(&1.stop_id, "entrance_", station_id))
      |> Enum.map(& &1.stop_id)

    Helpers.item(
      "naming_entrance_prefix",
      "Entrances use entrance_ prefix",
      if(flagged == [], do: :pass, else: :warn),
      :convention,
      length(flagged),
      flagged
    )
  end

  defp prefix_type_mismatch_check(child_stops, station_id) do
    flagged =
      child_stops
      |> Enum.flat_map(fn stop ->
        @prefix_type_map
        |> Enum.filter(fn {prefix, expected_type} ->
          has_type_prefix?(stop.stop_id, prefix, station_id) and
            stop.location_type != expected_type
        end)
        |> Enum.map(fn {prefix, expected_type} ->
          %{
            id: stop.stop_id,
            reason: "prefix #{prefix} implies type #{expected_type}, actual #{stop.location_type}"
          }
        end)
      end)

    Helpers.item(
      "naming_prefix_type_mismatch",
      "Stop ID prefix matches location_type",
      if(flagged == [], do: :pass, else: :warn),
      :warning,
      length(flagged),
      flagged
    )
  end

  defp has_type_prefix?(stop_id, prefix, station_id) do
    String.starts_with?(stop_id, prefix) or
      String.starts_with?(stop_id, station_id <> "_" <> prefix)
  end

  defp test_placeholder_check(stops) do
    flagged =
      Enum.flat_map(stops, fn stop ->
        id_match = has_test_token?(stop.stop_id)
        name_match = has_test_token?(stop.stop_name)

        if id_match or name_match do
          [%{id: stop.stop_id, reason: "contains test/placeholder token"}]
        else
          []
        end
      end)

    Helpers.item(
      "naming_test_placeholder",
      "Stop IDs and names free of test/placeholder tokens",
      if(flagged == [], do: :pass, else: :warn),
      :warning,
      length(flagged),
      flagged
    )
  end

  defp has_test_token?(nil), do: false

  defp has_test_token?(text) do
    downcased = String.downcase(text)
    Enum.any?(@test_tokens, &String.contains?(downcased, &1))
  end

  defp direction_mismatch_check(stops) do
    flagged =
      stops
      |> Enum.filter(&(Helpers.present?(&1.stop_id) and Helpers.present?(&1.stop_name)))
      |> Enum.flat_map(fn stop ->
        id_dirs = Helpers.extract_direction_tokens(stop.stop_id)
        name_dirs = Helpers.extract_direction_tokens(stop.stop_name)

        if MapSet.size(id_dirs) > 0 and MapSet.size(name_dirs) > 0 and
             not MapSet.equal?(id_dirs, name_dirs) do
          [
            %{
              id: stop.stop_id,
              reason:
                "ID: #{inspect(MapSet.to_list(id_dirs))}, name: #{inspect(MapSet.to_list(name_dirs))}"
            }
          ]
        else
          []
        end
      end)

    Helpers.item(
      "naming_direction_mismatch",
      "Stop ID and name directional consistency",
      if(flagged == [], do: :pass, else: :warn),
      :warning,
      length(flagged),
      flagged
    )
  end

  defp duplicate_id_tokens_check(stops) do
    flagged =
      stops
      |> Enum.flat_map(fn stop ->
        tokens = Helpers.tokenize_stop_id(stop.stop_id)

        meaningful =
          Enum.reject(tokens, fn t ->
            String.length(t) <= 1 or String.match?(t, ~r/^\d+$/)
          end)

        dupes = meaningful -- Enum.uniq(meaningful)

        if dupes != [] do
          [%{id: stop.stop_id, reason: "repeated: #{Enum.join(Enum.uniq(dupes), ", ")}"}]
        else
          []
        end
      end)

    Helpers.item(
      "naming_duplicate_id_tokens",
      "Stop IDs without repeated tokens",
      if(flagged == [], do: :pass, else: :warn),
      :convention,
      length(flagged),
      flagged
    )
  end

  defp autogenerated_name_check(stops) do
    flagged =
      stops
      |> Enum.filter(
        &(Helpers.present?(&1.stop_name) and Helpers.present?(&1.stop_id) and
            &1.location_type != 1)
      )
      |> Enum.filter(fn stop ->
        normalized_name =
          stop.stop_name |> String.downcase() |> String.replace(~r/\s+/, "_")

        normalized_id = String.downcase(stop.stop_id)
        normalized_name == normalized_id
      end)
      |> Enum.map(fn stop ->
        %{id: stop.stop_id, reason: "name looks auto-generated from stop_id"}
      end)

    Helpers.item(
      "naming_autogenerated_name",
      "Stop names appear human-written",
      if(flagged == [], do: :pass, else: :warn),
      :convention,
      length(flagged),
      flagged
    )
  end

  defp parent_name_consistency_check(station, child_stops) do
    station_tokens = meaningful_name_tokens(station.stop_name)

    flagged =
      if MapSet.size(station_tokens) == 0 do
        []
      else
        child_stops
        |> Enum.filter(&(&1.location_type in [0, 2] and Helpers.present?(&1.stop_name)))
        |> Enum.filter(fn stop ->
          child_tokens = meaningful_name_tokens(stop.stop_name)

          MapSet.size(child_tokens) > 0 and
            MapSet.size(MapSet.intersection(station_tokens, child_tokens)) == 0
        end)
        |> Enum.map(fn stop ->
          %{
            id: stop.stop_id,
            reason: "no shared name tokens with station \"#{station.stop_name}\""
          }
        end)
      end

    Helpers.item(
      "naming_parent_name_consistency",
      "Child stop names share tokens with station name",
      if(flagged == [], do: :pass, else: :warn),
      :convention,
      length(flagged),
      flagged
    )
  end

  defp meaningful_name_tokens(nil), do: MapSet.new()

  defp meaningful_name_tokens(name) do
    name
    |> String.downcase()
    |> String.split(~r/[\s_\-]+/, trim: true)
    |> Enum.reject(&(MapSet.member?(@name_minor_words, &1) or String.length(&1) <= 2))
    |> MapSet.new()
  end

  defp stop_id_typo_check(stops) do
    flagged =
      stops
      |> Enum.flat_map(fn stop ->
        Helpers.tokenize_stop_id(stop.stop_id)
        |> Enum.reject(fn token ->
          String.length(token) < 4 or String.match?(token, ~r/^\d+$/)
        end)
        |> Enum.reject(&MapSet.member?(@transit_terms, &1))
        |> Enum.flat_map(fn token ->
          case find_near_match(token) do
            nil -> []
            match -> [%{id: stop.stop_id, reason: "token '#{token}' near '#{match}'"}]
          end
        end)
      end)
      |> Enum.uniq_by(fn %{id: id, reason: reason} -> {id, reason} end)

    Helpers.item(
      "naming_stop_id_typos",
      "Stop ID tokens match transit vocabulary",
      if(flagged == [], do: :pass, else: :warn),
      :analysis,
      length(flagged),
      flagged
    )
  end

  defp find_near_match(token) do
    Enum.find(@transit_terms, fn term ->
      dist = Helpers.levenshtein(token, term)
      dist > 0 and dist <= 2
    end)
  end
end
