defmodule GtfsPlanner.Gtfs.StationReport2.NamingConventions do
  @moduledoc """
  Builder module for the Naming & ID Conventions section of Report 2.

  Calls `NamingChecks.validate/2`, selects 6 required checks,
  normalizes status to :pass | :fail, and normalizes detail shapes.
  """

  alias GtfsPlanner.Gtfs.StationReport.NamingChecks

  @check_config [
    %{
      id: "naming_title_case",
      label: "Stop name title case",
      rule: "All stop names use title case."
    },
    %{
      id: "naming_node_prefix",
      label: "Generic node ID prefix",
      rule: "All generic node IDs use the node_ prefix."
    },
    %{
      id: "naming_boarding_prefix",
      label: "Boarding area ID prefix",
      rule: "All boarding area IDs use the boarding_ prefix."
    },
    %{
      id: "naming_entrance_prefix",
      label: "Entrance ID prefix",
      rule: "All entrance/exit IDs use the entrance_ prefix."
    },
    %{
      id: "naming_prefix_type_mismatch",
      label: "Stop ID prefix \u2014 location type match",
      rule: "All stop ID prefixes match their location type."
    },
    %{
      id: "naming_autogenerated_name",
      label: "Stop names \u2014 human-written",
      rule: "All stop names appear human-written."
    }
  ]

  @prefix_type_map %{
    2 => "entrance_",
    3 => "node_",
    4 => "boarding_"
  }

  @spec build(%{station: map(), child_stops: [map()]}) :: [map()]
  def build(%{station: station, child_stops: child_stops}) do
    legacy_checks = NamingChecks.validate(station, child_stops)
    legacy_index = Map.new(legacy_checks, fn check -> {check.id, check} end)

    stop_index =
      Map.new([station | child_stops], fn stop -> {stop.stop_id, stop} end)

    Enum.map(@check_config, fn config ->
      legacy = Map.get(legacy_index, config.id)
      build_check(config, legacy, stop_index)
    end)
  end

  defp build_check(config, nil, _stop_index) do
    %{
      id: config.id,
      label: config.label,
      rule: config.rule,
      status: :pass,
      issue_count: 0,
      details: []
    }
  end

  defp build_check(config, legacy, stop_index) do
    status = normalize_status(legacy.status)
    details = normalize_details(config.id, legacy.details, stop_index)

    %{
      id: config.id,
      label: config.label,
      rule: config.rule,
      status: status,
      issue_count: length(details),
      details: details
    }
  end

  defp normalize_status(:pass), do: :pass
  defp normalize_status(_), do: :fail

  defp normalize_details(_id, nil, _stop_index), do: []
  defp normalize_details(_id, details, _stop_index) when not is_list(details), do: []

  defp normalize_details("naming_title_case", details, stop_index) do
    Enum.map(details, fn detail ->
      stop_id = detail.id
      stop = Map.get(stop_index, stop_id)

      %{
        stop_id: stop_id,
        stop_name: get_stop_field(stop, :stop_name),
        location_type: get_stop_field(stop, :location_type),
        expected_prefix: nil
      }
    end)
  end

  defp normalize_details("naming_prefix_type_mismatch", details, stop_index) do
    Enum.map(details, fn detail ->
      stop_id = detail.id
      stop = Map.get(stop_index, stop_id)
      location_type = get_stop_field(stop, :location_type)

      %{
        stop_id: stop_id,
        stop_name: get_stop_field(stop, :stop_name),
        location_type: location_type,
        expected_prefix: Map.get(@prefix_type_map, location_type)
      }
    end)
  end

  defp normalize_details("naming_autogenerated_name", details, stop_index) do
    Enum.map(details, fn detail ->
      stop_id = detail.id
      stop = Map.get(stop_index, stop_id)

      %{
        stop_id: stop_id,
        stop_name: get_stop_field(stop, :stop_name),
        location_type: get_stop_field(stop, :location_type),
        expected_prefix: nil
      }
    end)
  end

  defp normalize_details(_id, details, _stop_index) do
    Enum.map(details, fn detail ->
      stop_id = if is_map(detail), do: detail.id, else: detail

      %{
        stop_id: stop_id,
        stop_name: nil,
        location_type: nil,
        expected_prefix: nil
      }
    end)
  end

  defp get_stop_field(nil, _field), do: nil
  defp get_stop_field(stop, field), do: Map.get(stop, field)
end
