defmodule GtfsPlanner.Gtfs.StationReport2.NamingConventionsTest do
  use ExUnit.Case, async: true

  alias GtfsPlanner.Gtfs.StationReport2.NamingConventions

  @required_keys ~w(id label rule status issue_count details)a
  @detail_keys ~w(stop_id stop_name location_type expected_prefix)a

  @expected_ids [
    "naming_title_case",
    "naming_node_prefix",
    "naming_boarding_prefix",
    "naming_entrance_prefix",
    "naming_prefix_type_mismatch",
    "naming_autogenerated_name"
  ]

  defp make_station(attrs \\ %{}) do
    Map.merge(
      %{
        stop_id: "STATION_1",
        stop_name: "Test Station",
        location_type: 1,
        parent_station: nil,
        wheelchair_boarding: nil,
        level_id: nil,
        stop_lat: nil,
        stop_lon: nil
      },
      attrs
    )
  end

  defp make_stop(attrs) do
    Map.merge(
      %{
        stop_name: "Stop",
        wheelchair_boarding: nil,
        level_id: nil,
        stop_lat: nil,
        stop_lon: nil
      },
      attrs
    )
  end

  describe "build/1" do
    test "returns exactly 6 checks with all required keys" do
      checks = NamingConventions.build(%{station: make_station(), child_stops: []})

      assert length(checks) == 6

      Enum.each(checks, fn check ->
        Enum.each(@required_keys, fn key ->
          assert Map.has_key?(check, key), "Missing key #{key} in check #{check.id}"
        end)
      end)
    end

    test "checks are in the correct order" do
      checks = NamingConventions.build(%{station: make_station(), child_stops: []})
      ids = Enum.map(checks, & &1.id)
      assert ids == @expected_ids
    end

    test "all-valid fixture returns all PASS with zero issues and empty details" do
      station = make_station(%{stop_name: "Test Station"})

      entrance =
        make_stop(%{
          stop_id: "entrance_main",
          stop_name: "Main Entrance",
          location_type: 2,
          parent_station: "STATION_1"
        })

      node =
        make_stop(%{
          stop_id: "node_center",
          stop_name: "Center Node",
          location_type: 3,
          parent_station: "STATION_1"
        })

      boarding =
        make_stop(%{
          stop_id: "boarding_a",
          stop_name: "Boarding Platform Alpha",
          location_type: 4,
          parent_station: "STATION_1"
        })

      checks =
        NamingConventions.build(%{station: station, child_stops: [entrance, node, boarding]})

      Enum.each(checks, fn check ->
        assert check.status == :pass, "Check #{check.id} should pass but got #{check.status}"
        assert check.issue_count == 0, "Check #{check.id} should have 0 issues"
        assert check.details == [], "Check #{check.id} should have empty details"
      end)
    end

    test "title case violation includes stop_id, stop_name, and location_type" do
      station = make_station(%{stop_name: "test station"})

      checks = NamingConventions.build(%{station: station, child_stops: []})
      check = Enum.find(checks, &(&1.id == "naming_title_case"))

      assert check.status == :fail
      assert check.issue_count > 0

      Enum.each(check.details, fn detail ->
        Enum.each(@detail_keys, fn key ->
          assert Map.has_key?(detail, key), "Missing detail key #{key}"
        end)

        assert detail.stop_id == "STATION_1"
        assert detail.stop_name == "test station"
        assert detail.location_type == 1
      end)
    end

    test "prefix mismatch includes expected_prefix" do
      # An entrance with a boarding_ prefix triggers a mismatch
      mismatched =
        make_stop(%{
          stop_id: "boarding_north",
          stop_name: "North Entrance",
          location_type: 2,
          parent_station: "STATION_1"
        })

      checks = NamingConventions.build(%{station: make_station(), child_stops: [mismatched]})
      check = Enum.find(checks, &(&1.id == "naming_prefix_type_mismatch"))

      assert check.status == :fail
      assert check.issue_count > 0

      detail = hd(check.details)
      assert detail.stop_id == "boarding_north"
      assert detail.location_type == 2
      assert detail.expected_prefix == "entrance_"
    end

    test "legacy :warn maps to :fail" do
      # Generic node without node_ prefix triggers :warn in NamingChecks
      bad_node =
        make_stop(%{
          stop_id: "generic_connector",
          stop_name: "Connector",
          location_type: 3,
          parent_station: "STATION_1"
        })

      checks = NamingConventions.build(%{station: make_station(), child_stops: [bad_node]})
      check = Enum.find(checks, &(&1.id == "naming_node_prefix"))

      assert check.status == :fail
    end

    test "unknown stop_id in details keeps optional fields nil" do
      # Build with a station that has title case issues, then verify
      # that if a stop references an unknown ID, nil fields are returned.
      # We test this by checking prefix checks with stops that have IDs
      # not in the stop_index — but since NamingChecks only returns IDs
      # from the input stops, we verify nil handling via the normalize path.
      station = make_station()
      checks = NamingConventions.build(%{station: station, child_stops: []})

      # All prefix checks should pass with empty details for no child stops
      prefix_checks =
        Enum.filter(checks, fn c ->
          c.id in ["naming_node_prefix", "naming_boarding_prefix", "naming_entrance_prefix"]
        end)

      Enum.each(prefix_checks, fn check ->
        assert check.status == :pass
        assert check.details == []
      end)
    end

    test "detail entries contain only the specified keys" do
      station = make_station(%{stop_name: "bad name"})

      checks = NamingConventions.build(%{station: station, child_stops: []})
      check = Enum.find(checks, &(&1.id == "naming_title_case"))

      Enum.each(check.details, fn detail ->
        assert Map.keys(detail) |> Enum.sort() == Enum.sort(@detail_keys)
      end)
    end

    test "autogenerated name check flags matching ID and name" do
      auto_stop =
        make_stop(%{
          stop_id: "node_auto",
          stop_name: "Node Auto",
          location_type: 3,
          parent_station: "STATION_1"
        })

      checks = NamingConventions.build(%{station: make_station(), child_stops: [auto_stop]})
      check = Enum.find(checks, &(&1.id == "naming_autogenerated_name"))

      assert check.status == :fail
      assert check.issue_count == 1

      detail = hd(check.details)
      assert detail.stop_id == "node_auto"
      assert detail.stop_name == "Node Auto"
      assert detail.location_type == 3
    end

    test "entrance prefix check flags missing prefix" do
      bad_entrance =
        make_stop(%{
          stop_id: "door_main",
          stop_name: "Main Door",
          location_type: 2,
          parent_station: "STATION_1"
        })

      checks = NamingConventions.build(%{station: make_station(), child_stops: [bad_entrance]})
      check = Enum.find(checks, &(&1.id == "naming_entrance_prefix"))

      assert check.status == :fail
      assert check.issue_count == 1
      assert hd(check.details).stop_id == "door_main"
    end

    test "boarding prefix check flags missing prefix" do
      bad_boarding =
        make_stop(%{
          stop_id: "area_a",
          stop_name: "Area A",
          location_type: 4,
          parent_station: "STATION_1"
        })

      checks = NamingConventions.build(%{station: make_station(), child_stops: [bad_boarding]})
      check = Enum.find(checks, &(&1.id == "naming_boarding_prefix"))

      assert check.status == :fail
      assert check.issue_count == 1
      assert hd(check.details).stop_id == "area_a"
    end
  end
end
