#!/bin/bash

environment="$1"
echo "environment=$environment"

tofu -chdir=infra/config init >/dev/null
tofu -chdir=infra/config apply -auto-approve > /dev/null || true

network_name=$(tofu -chdir=infra/config output -json environments | jq -r --arg env "$environment" '.[$env].network_name // ""')
echo "network=$network_name"

account_name=$(tofu -chdir=infra/config output -json networks | jq -r --arg net "$network_name" '.[$net].account_name // ""')
echo "account_name=$account_name"

backend_config_file="infra/accounts/$account_name.s3.tfbackend"

if [[ -f "$backend_config_file" ]]; then
  backend_config=$(basename "$backend_config_file")
  echo "backend_config=$backend_config"

  account_id=$(grep "bucket\s*=" "$backend_config_file" | sed 's/^.*[^0-9]\([0-9]\{12\}\)[^0-9].*$/\1/')
  echo "account_id=$account_id"

  region=$(grep "region\s*=" "$backend_config_file" | sed 's/^.*=.*"\(.*\)"$/\1/')
  echo "region=$region"
else
  echo "backend_config_file $backend_config_file not found"
  account_id=""
  region=""
fi

github_actions_role_name=$(tofu -chdir=infra/config output -raw github_actions_role_name)
echo "github_actions_role_name=$github_actions_role_name"

if [[ -n "$account_id" ]]; then
  github_actions_role_arn="arn:aws:iam::$account_id:role/$github_actions_role_name"
else
  github_actions_role_arn=""
fi
echo "github_actions_role_arn=$github_actions_role_arn"

project_name=$(tofu -chdir=infra/config output -raw project_name)
echo "project_name=$project_name"

host=$(tofu -chdir=infra/config output -json environments | jq -r --arg env "$environment" '.[$env].host // ""')
echo "host=$host"

if [[ -z "$host" ]]; then
  repository_url="$account_id".dkr.ecr."$region".amazonaws.com/"$project_name"
else
  repository_url="$project_name"
fi
echo "repository_url=$repository_url"
