name: Deploy
run-name: Deploy ${{inputs.version || 'main' }} to ${{ inputs.environment || 'dev' }} environment
concurrency:
  group: cd-${{inputs.version || 'main' }}-${{ inputs.environment || 'dev' }}
  cancel-in-progress: true

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        required: true
        default: "dev"
        type: choice
        options:
          - dev
      version:
        required: true
        default: "main"
        description: Tag or branch or SHA to deploy

permissions:
  contents: read
  id-token: write

env:
  MISE_AUTO_INSTALL: 0

jobs:
  build_publish:
    name: Build/publish
    runs-on: ${{ fromJSON(vars.GH_DOCKER_RUNNER_LABEL) }}
    timeout-minutes: 30
    env:
      DEV_IP: ${{ vars.DEV_IP }}
    steps:
      - name: Set environment configuration
        run: |
          echo "environment=${{ inputs.environment || 'dev' }}" >> $GITHUB_ENV
          echo "version=${{ inputs.version || 'main' }}" >> $GITHUB_ENV
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3
        with:
          install: true
          install_args: "opentofu"
          cache: true
      - uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd # v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Add known hosts
        run: ssh-keyscan -H "${{ vars.DEV_IP }}" >> ~/.ssh/known_hosts
      - name: Gather account information
        run: |
          source mise-tasks/infra/account-information $environment

          echo "REPOSITORY_URL=$repository_url" >> $GITHUB_ENV
          echo "AWS_REGION=$region" >> $GITHUB_ENV
          echo "AWS_ROLE_TO_ASSUME=$github_actions_role_arn" >> $GITHUB_ENV
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          path: build
          ref: ${{ env.version }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
      - name: Build/publish
        run: mise run infra:environment:build "$environment" --build-dir build --push

  deploy:
    name: Deploy
    runs-on: ${{ fromJSON(vars.GH_RUNNER_LABEL) }}
    timeout-minutes: 30
    needs: [build_publish]
    environment: ${{ inputs.environment || 'dev' }}
    env:
      DEV_IP: ${{ vars.DEV_IP }}
      GEOAPIFY_API_KEY: ${{ secrets.GEOAPIFY_API_KEY }}

    steps:
      - name: Set environment configuration
        run: |
          echo "environment=${{ inputs.environment || 'dev' }}" >> $GITHUB_ENV
          echo "version=${{ inputs.version || 'main' }}" >> $GITHUB_ENV
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3
        with:
          install: true
          install_args: "opentofu"
          cache: true
      - uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd # v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Add known hosts
        run: ssh-keyscan -H "${{ vars.DEV_IP }}" >> ~/.ssh/known_hosts
      - name: Gather account information
        run: |
          source mise-tasks/infra/account-information $environment

          echo "REPOSITORY_URL=$repository_url" >> $GITHUB_ENV
          echo "AWS_REGION=$region" >> $GITHUB_ENV
          echo "AWS_ROLE_TO_ASSUME=$github_actions_role_arn" >> $GITHUB_ENV
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          path: build
          ref: ${{ env.version }}
      - name: Deploy
        run: mise run infra:environment:deploy "$environment" --build-dir build
